# Generated by Django 5.0.3 on 2024-11-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('numero_candidatos', models.PositiveIntegerField()),
                ('numero_provas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='concurso_app.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Examinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinadores', to='concurso_app.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('eliminatoria', models.BooleanField(default=False)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='concurso_app.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concurso_app.candidato')),
                ('examinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concurso_app.examinador')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concurso_app.prova')),
            ],
        ),
    ]
